application:
  mqtt:
    protocol: "${MQTT_PROTOCOL:tcp}"
    host: "${MQTT_HOST:localhost}"
    port: "${MQTT_PORT:1883}"
    topic: "${MQTT_TOPIC:HEALTH}"
  userIds: >
    854e18b9-c8e3-4440-bf77-ffbdc35e1b97,
    5bff95b5-6eca-479a-befc-9819f51ccf6f,
    c2a14ef9-5185-44fd-bbef-c69df88fc72d,
    f72904c2-5648-4396-9b04-a7233c2ba6a9,
    e3f4a484-03c4-4172-9888-7da4110a4ef3
  data:
    spo2: so2-sample-exhausted.csv
    ecg: ecg.csv
    ecg_dead: ecg-dead.csv


server:
  port: "${INTERNAL_SERVICE_PORT:8080}"
